"""second add

Revision ID: 751e804adf25
Revises: dfb617bb38c6
Create Date: 2022-07-28 23:02:02.730901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '751e804adf25'
down_revision = 'dfb617bb38c6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Column('dt', sa.DateTime())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
